//Source of the files:
//http://theremin.music.uiowa.edu/MISpiano.html

import A0 from './PianoNotes/Piano.ff.A0.mp3';
import A1 from './PianoNotes/Piano.ff.A1.mp3';
import A2 from './PianoNotes/Piano.ff.A2.mp3';
import A3 from './PianoNotes/Piano.ff.A3.mp3';
import A4 from './PianoNotes/Piano.ff.A4.mp3';
import A5 from './PianoNotes/Piano.ff.A5.mp3';
import A6 from './PianoNotes/Piano.ff.A6.mp3';
import A7 from './PianoNotes/Piano.ff.A7.mp3';
import Ab1 from './PianoNotes/Piano.ff.Ab1.mp3';
import Ab2 from './PianoNotes/Piano.ff.Ab2.mp3';
import Ab3 from './PianoNotes/Piano.ff.Ab3.mp3';
import Ab4 from './PianoNotes/Piano.ff.Ab4.mp3';
import Ab5 from './PianoNotes/Piano.ff.Ab5.mp3';
import Ab6 from './PianoNotes/Piano.ff.Ab6.mp3';
import Ab7 from './PianoNotes/Piano.ff.Ab7.mp3';
import B0 from './PianoNotes/Piano.ff.B0.mp3';
import B1 from './PianoNotes/Piano.ff.B1.mp3';
import B2 from './PianoNotes/Piano.ff.B2.mp3';
import B3 from './PianoNotes/Piano.ff.B3.mp3';
import B4 from './PianoNotes/Piano.ff.B4.mp3';
import B5 from './PianoNotes/Piano.ff.B5.mp3';
import B6 from './PianoNotes/Piano.ff.B6.mp3';
import B7 from './PianoNotes/Piano.ff.B7.mp3';
import Bb0 from './PianoNotes/Piano.ff.Bb0.mp3';
import Bb1 from './PianoNotes/Piano.ff.Bb1.mp3';
import Bb2 from './PianoNotes/Piano.ff.Bb2.mp3';
import Bb3 from './PianoNotes/Piano.ff.Bb3.mp3';
import Bb4 from './PianoNotes/Piano.ff.Bb4.mp3';
import Bb5 from './PianoNotes/Piano.ff.Bb5.mp3';
import Bb6 from './PianoNotes/Piano.ff.Bb6.mp3';
import Bb7 from './PianoNotes/Piano.ff.Bb7.mp3';
import C1 from './PianoNotes/Piano.ff.C1.mp3';
import C2 from './PianoNotes/Piano.ff.C2.mp3';
import C3 from './PianoNotes/Piano.ff.C3.mp3';
import C4 from './PianoNotes/Piano.ff.C4.mp3';
import C5 from './PianoNotes/Piano.ff.C5.mp3';
import C6 from './PianoNotes/Piano.ff.C6.mp3';
import C7 from './PianoNotes/Piano.ff.C7.mp3';
import C8 from './PianoNotes/Piano.ff.C8.mp3';
import D1 from './PianoNotes/Piano.ff.D1.mp3';
import D2 from './PianoNotes/Piano.ff.D2.mp3';
import D3 from './PianoNotes/Piano.ff.D3.mp3';
import D4 from './PianoNotes/Piano.ff.D4.mp3';
import D5 from './PianoNotes/Piano.ff.D5.mp3';
import D6 from './PianoNotes/Piano.ff.D6.mp3';
import D7 from './PianoNotes/Piano.ff.D7.mp3';
import Db1 from './PianoNotes/Piano.ff.Db1.mp3';
import Db2 from './PianoNotes/Piano.ff.Db2.mp3';
import Db3 from './PianoNotes/Piano.ff.Db3.mp3';
import Db4 from './PianoNotes/Piano.ff.Db4.mp3';
import Db5 from './PianoNotes/Piano.ff.Db5.mp3';
import Db6 from './PianoNotes/Piano.ff.Db6.mp3';
import Db7 from './PianoNotes/Piano.ff.Db7.mp3';
import E1 from './PianoNotes/Piano.ff.E1.mp3';
import E2 from './PianoNotes/Piano.ff.E2.mp3';
import E3 from './PianoNotes/Piano.ff.E3.mp3';
import E4 from './PianoNotes/Piano.ff.E4.mp3';
import E5 from './PianoNotes/Piano.ff.E5.mp3';
import E6 from './PianoNotes/Piano.ff.E6.mp3';
import E7 from './PianoNotes/Piano.ff.E7.mp3';
import Eb1 from './PianoNotes/Piano.ff.Eb1.mp3';
import Eb2 from './PianoNotes/Piano.ff.Eb2.mp3';
import Eb3 from './PianoNotes/Piano.ff.Eb3.mp3';
import Eb4 from './PianoNotes/Piano.ff.Eb4.mp3';
import Eb5 from './PianoNotes/Piano.ff.Eb5.mp3';
import Eb6 from './PianoNotes/Piano.ff.Eb6.mp3';
import Eb7 from './PianoNotes/Piano.ff.Eb7.mp3';
import F1 from './PianoNotes/Piano.ff.F1.mp3';
import F2 from './PianoNotes/Piano.ff.F2.mp3';
import F3 from './PianoNotes/Piano.ff.F3.mp3';
import F4 from './PianoNotes/Piano.ff.F4.mp3';
import F5 from './PianoNotes/Piano.ff.F5.mp3';
import F6 from './PianoNotes/Piano.ff.F6.mp3';
import F7 from './PianoNotes/Piano.ff.F7.mp3';
import G1 from './PianoNotes/Piano.ff.G1.mp3';
import G2 from './PianoNotes/Piano.ff.G2.mp3';
import G3 from './PianoNotes/Piano.ff.G3.mp3';
import G4 from './PianoNotes/Piano.ff.G4.mp3';
import G5 from './PianoNotes/Piano.ff.G5.mp3';
import G6 from './PianoNotes/Piano.ff.G6.mp3';
import G7 from './PianoNotes/Piano.ff.G7.mp3';
import Gb1 from './PianoNotes/Piano.ff.Gb1.mp3';
import Gb2 from './PianoNotes/Piano.ff.Gb2.mp3';
import Gb3 from './PianoNotes/Piano.ff.Gb3.mp3';
import Gb4 from './PianoNotes/Piano.ff.Gb4.mp3';
import Gb5 from './PianoNotes/Piano.ff.Gb5.mp3';
import Gb6 from './PianoNotes/Piano.ff.Gb6.mp3';
import Gb7 from './PianoNotes/Piano.ff.Gb7.mp3';

export default function playPiano(id,volume) {
    let audio;
    switch (id) {
        case 'A0': audio = new Audio(A0); audio.volume = volume; audio.play(); break;
        case 'A1': audio = new Audio(A1); audio.volume = volume; audio.play(); break;
        case 'A2': audio = new Audio(A2); audio.volume = volume; audio.play(); break;
        case 'A3': audio = new Audio(A3); audio.volume = volume; audio.play(); break;
        case 'A4': audio = new Audio(A4); audio.volume = volume; audio.play(); break;
        case 'A5': audio = new Audio(A5); audio.volume = volume; audio.play(); break;
        case 'A6': audio = new Audio(A6); audio.volume = volume; audio.play(); break;
        case 'A7': audio = new Audio(A7); audio.volume = volume; audio.play(); break;
        case 'Ab1': audio = new Audio(Ab1); audio.volume = volume; audio.play(); break;
        case 'Ab2': audio = new Audio(Ab2); audio.volume = volume; audio.play(); break;
        case 'Ab3': audio = new Audio(Ab3); audio.volume = volume; audio.play(); break;
        case 'Ab4': audio = new Audio(Ab4); audio.volume = volume; audio.play(); break;
        case 'Ab5': audio = new Audio(Ab5); audio.volume = volume; audio.play(); break;
        case 'Ab6': audio = new Audio(Ab6); audio.volume = volume; audio.play(); break;
        case 'Ab7': audio = new Audio(Ab7); audio.volume = volume; audio.play(); break;
        case 'B0': audio = new Audio(B0); audio.volume = volume; audio.play(); break;
        case 'B1': audio = new Audio(B1); audio.volume = volume; audio.play(); break;
        case 'B2': audio = new Audio(B2); audio.volume = volume; audio.play(); break;
        case 'B3': audio = new Audio(B3); audio.volume = volume; audio.play(); break;
        case 'B4': audio = new Audio(B4); audio.volume = volume; audio.play(); break;
        case 'B5': audio = new Audio(B5); audio.volume = volume; audio.play(); break;
        case 'B6': audio = new Audio(B6); audio.volume = volume; audio.play(); break;
        case 'B7': audio = new Audio(B7); audio.volume = volume; audio.play(); break;
        case 'Bb0': audio = new Audio(Bb0); audio.volume = volume; audio.play(); break;
        case 'Bb1': audio = new Audio(Bb1); audio.volume = volume; audio.play(); break;
        case 'Bb2': audio = new Audio(Bb2); audio.volume = volume; audio.play(); break;
        case 'Bb3': audio = new Audio(Bb3); audio.volume = volume; audio.play(); break;
        case 'Bb4': audio = new Audio(Bb4); audio.volume = volume; audio.play(); break;
        case 'Bb5': audio = new Audio(Bb5); audio.volume = volume; audio.play(); break;
        case 'Bb6': audio = new Audio(Bb6); audio.volume = volume; audio.play(); break;
        case 'Bb7': audio = new Audio(Bb7); audio.volume = volume; audio.play(); break;
        case 'C1': audio = new Audio(C1); audio.volume = volume; audio.play(); break;
        case 'C2': audio = new Audio(C2); audio.volume = volume; audio.play(); break;
        case 'C3': audio = new Audio(C3); audio.volume = volume; audio.play(); break;
        case 'C4': audio = new Audio(C4); audio.volume = volume; audio.play(); break;
        case 'C5': audio = new Audio(C5); audio.volume = volume; audio.play(); break;
        case 'C6': audio = new Audio(C6); audio.volume = volume; audio.play(); break;
        case 'C7': audio = new Audio(C7); audio.volume = volume; audio.play(); break;
        case 'C8': audio = new Audio(C8); audio.volume = volume; audio.play(); break;
        case 'D1': audio = new Audio(D1); audio.volume = volume; audio.play(); break;
        case 'D2': audio = new Audio(D2); audio.volume = volume; audio.play(); break;
        case 'D3': audio = new Audio(D3); audio.volume = volume; audio.play(); break;
        case 'D4': audio = new Audio(D4); audio.volume = volume; audio.play(); break;
        case 'D5': audio = new Audio(D5); audio.volume = volume; audio.play(); break;
        case 'D6': audio = new Audio(D6); audio.volume = volume; audio.play(); break;
        case 'D7': audio = new Audio(D7); audio.volume = volume; audio.play(); break;
        case 'Db1': audio = new Audio(Db1); audio.volume = volume; audio.play(); break;
        case 'Db2': audio = new Audio(Db2); audio.volume = volume; audio.play(); break;
        case 'Db3': audio = new Audio(Db3); audio.volume = volume; audio.play(); break;
        case 'Db4': audio = new Audio(Db4); audio.volume = volume; audio.play(); break;
        case 'Db5': audio = new Audio(Db5); audio.volume = volume; audio.play(); break;
        case 'Db6': audio = new Audio(Db6); audio.volume = volume; audio.play(); break;
        case 'Db7': audio = new Audio(Db7); audio.volume = volume; audio.play(); break;
        case 'E1': audio = new Audio(E1); audio.volume = volume; audio.play(); break;
        case 'E2': audio = new Audio(E2); audio.volume = volume; audio.play(); break;
        case 'E3': audio = new Audio(E3); audio.volume = volume; audio.play(); break;
        case 'E4': audio = new Audio(E4); audio.volume = volume; audio.play(); break;
        case 'E5': audio = new Audio(E5); audio.volume = volume; audio.play(); break;
        case 'E6': audio = new Audio(E6); audio.volume = volume; audio.play(); break;
        case 'E7': audio = new Audio(E7); audio.volume = volume; audio.play(); break;
        case 'Eb1': audio = new Audio(Eb1); audio.volume = volume; audio.play(); break;
        case 'Eb2': audio = new Audio(Eb2); audio.volume = volume; audio.play(); break;
        case 'Eb3': audio = new Audio(Eb3); audio.volume = volume; audio.play(); break;
        case 'Eb4': audio = new Audio(Eb4); audio.volume = volume; audio.play(); break;
        case 'Eb5': audio = new Audio(Eb5); audio.volume = volume; audio.play(); break;
        case 'Eb6': audio = new Audio(Eb6); audio.volume = volume; audio.play(); break;
        case 'Eb7': audio = new Audio(Eb7); audio.volume = volume; audio.play(); break;
        case 'F1': audio = new Audio(F1); audio.volume = volume; audio.play(); break;
        case 'F2': audio = new Audio(F2); audio.volume = volume; audio.play(); break;
        case 'F3': audio = new Audio(F3); audio.volume = volume; audio.play(); break;
        case 'F4': audio = new Audio(F4); audio.volume = volume; audio.play(); break;
        case 'F5': audio = new Audio(F5); audio.volume = volume; audio.play(); break;
        case 'F6': audio = new Audio(F6); audio.volume = volume; audio.play(); break;
        case 'F7': audio = new Audio(F7); audio.volume = volume; audio.play(); break;
        case 'G1': audio = new Audio(G1); audio.volume = volume; audio.play(); break;
        case 'G2': audio = new Audio(G2); audio.volume = volume; audio.play(); break;
        case 'G3': audio = new Audio(G3); audio.volume = volume; audio.play(); break;
        case 'G4': audio = new Audio(G4); audio.volume = volume; audio.play(); break;
        case 'G5': audio = new Audio(G5); audio.volume = volume; audio.play(); break;
        case 'G6': audio = new Audio(G6); audio.volume = volume; audio.play(); break;
        case 'G7': audio = new Audio(G7); audio.volume = volume; audio.play(); break;
        case 'Gb1': audio = new Audio(Gb1); audio.volume = volume; audio.play(); break;
        case 'Gb2': audio = new Audio(Gb2); audio.volume = volume; audio.play(); break;
        case 'Gb3': audio = new Audio(Gb3); audio.volume = volume; audio.play(); break;
        case 'Gb4': audio = new Audio(Gb4); audio.volume = volume; audio.play(); break;
        case 'Gb5': audio = new Audio(Gb5); audio.volume = volume; audio.play(); break;
        case 'Gb6': audio = new Audio(Gb6); audio.volume = volume; audio.play(); break;
        case 'Gb7': audio = new Audio(Gb7); audio.volume = volume; audio.play(); break;

        default: break;
    }
}